"""initial_schema

Revision ID: 7f733bd0ea52
Revises: 
Create Date: 2026-05-27 16:33:59.593178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f733bd0ea52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contact_lists_organization_id'), 'contact_lists', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_import_history_organization_id'), 'import_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_conversations_organization_id'), 'whatsapp_conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_organization_id'), 'whatsapp_templates', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_templates_organization_id'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_conversations_organization_id'), table_name='whatsapp_conversations')
    op.drop_index(op.f('ix_import_history_organization_id'), table_name='import_history')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_index(op.f('ix_contact_lists_organization_id'), table_name='contact_lists')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    # ### end Alembic commands ###
